MvcRouteMap/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcRouteMap.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvcRouteMap/Controllers/RouteMapController.cs
using MvcRouteMap.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MvcRouteMap.Controllers
{
    public class RouteMapController : Controller
    {
        public async Task<ActionResult> RouteTotalDistanceRecursively(string inputGraph, string route)
        {
            var mapService = new MapService();
            var result = await mapService.GetRouteTotalDistanceRecursivelyAsync(inputGraph, route);
            if (Request.IsAjaxRequest())
                return PartialView("_pwRouteTotalDistanceRecursevly", result);
            else
                return View(result);
        }

        public async Task<ActionResult> ShortestRouteBetweenTwoTowns(string inputGraph, string route)
        {
            var mapService = new MapService();
            var result = await mapService.GetShortestRouteBetweenTwoTownsAsync(inputGraph, route);
            if (Request.IsAjaxRequest())
                return PartialView("_pwShortestRouteBetweenTwoTowns", result);
            else
                return View(result);
        }

        public async Task<ActionResult> RoutesWithMaxStops(string inputGraph, string route, string maxStops)
        {
            var mapService = new MapService();
            var result = await mapService.GetRoutesWithMaxStopsAsync(inputGraph, route, int.Parse(maxStops));
            if (Request.IsAjaxRequest())
                return PartialView("_pwRoutesWithMaxStops", result);
            else
                return View(result);
        }
        
        public async Task<ActionResult> RouteTotalDistanceNotRecursively(string inputGraph, string route)
        {
            var mapService = new MapService();
            var result = await mapService.GetRouteTotalDistanceAsync(inputGraph, route);
            if (Request.IsAjaxRequest())
                return PartialView("_pwRouteTotalDistanceNotRecursevly", result);
            else
                return View(result);
        }

    }
}

MvcRouteMap/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

MvcRouteMap/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>(68) 9968-4517</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>(68) 9968-4517</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:naisel@gmail.com">nraisel@gmail.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:naisel@gmail.com">nraisel@gmail.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:naisel@gmail.com">nraisel@gmail.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        Rua Farroupilha 181.<br />
        Rio Branco, AC. CEP: 69900-559
    </p>
</section>

MvcRouteMap/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<h2>Total Distance of any Route</h2>
<br />
@using (Ajax.BeginForm("RouteTotalDistanceRecursively", "RouteMap",
            new AjaxOptions
            {
                UpdateTargetId = "content",
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                LoadingElementId = "loaderB64",
                LoadingElementDuration = 2500
            }))
{
    <label for="inputGraph">Input the Directed Graph: </label>
    <input id="inputGraph" name="inputGraph" class="length" type="text" value="AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" placeholder="Ex. AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" />
    
    <label for="route">Input the Route: </label>
    <input id="route" name="route" class="length" type="text" value="" placeholder="Ex. A-B-C" />
    <br />
    
    <input type="submit" value="Compute Total Distance of Route" />
 }
<br />

<div id="content"></div>

<br />

<hr />

<h2>Shortest Route Between Two Towns</h2>
<br />
@using (Ajax.BeginForm("ShortestRouteBetweenTwoTowns", "RouteMap",
            new AjaxOptions
            {
                UpdateTargetId = "shcontent",
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                LoadingElementId = "loaderB64",
                LoadingElementDuration = 2500
            }))
{
    <label for="inputGraph">Input the Directed Graph: </label>
    <input id="inputGraph" name="inputGraph" class="length" type="text" value="AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" placeholder="Ex. AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" />
    
    <label for="route">Input the Route: </label>
    <input id="route" name="route" class="length" type="text" value="" placeholder="Ex. A-C" />
    <br />
    
    <input type="submit" value="Compute the Shortest Route" />
 }
<br />

<div id="shcontent"></div>
<br />

<hr />

<h2>All Available Routes between two towns with a maximum of n stops </h2>
<br />
@using (Ajax.BeginForm("RoutesWithMaxStops", "RouteMap",
            new AjaxOptions
            {
                UpdateTargetId = "avecontent",
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                LoadingElementId = "loaderB64",
                LoadingElementDuration = 2500
            }))
{
    <label for="inputGraph">Input the Directed Graph: </label>
    <input id="inputGraph" name="inputGraph" class="length" type="text" value="AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" placeholder="Ex. AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" />
    
    <label for="route">Input the Route: </label>
    <input id="route" name="route" class="length" type="text" value="" placeholder="Ex. A-D" />
    
    <label for="maxStops">Input Maximum of Stops: </label>
    <input id="maxStops" name="maxStops" class="length" type="text" value="3" placeholder="Ex. 3" />
    <br />
    
    <input type="submit" value="Compute All Available Routes" />
 }
<br />
<div id="avecontent"></div>

<br />

<hr />
<h2>Total Distance of any Route (Not Recursevly)</h2>
<br />
@using (Ajax.BeginForm("RouteTotalDistanceNotRecursively", "RouteMap",
            new AjaxOptions
            {
                UpdateTargetId = "contentNotR",
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                LoadingElementId = "loaderB64",
                LoadingElementDuration = 2500
            }))
{
    <label for="inputGraph">Input the Directed Graph: </label>
    <input id="inputGraph" name="inputGraph" class="length" type="text" value="AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" placeholder="Ex. AB5, BC4, CD8, DC8, DE6, AD5, CE2, EB3, AE7" />
    
    <label for="route">Input the Route: </label>
    <input id="route" name="route" class="length" type="text" value="" placeholder="Ex. A-B-C" />
    <br />
    
    <input type="submit" value="Compute Total Distance of Route" />
 }
<br />

<div id="contentNotR"></div>